import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { ThemeToggle } from "@/components/theme/theme-toggle";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300","400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.variable}  antialiased`}
      >
          <ThemeProvider
          attribute="class"
          defaultTheme="light"
          // forcedTheme="light"
          // disableTransitionOnChange
        >
          <ThemeToggle />
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
